cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: us-east-1
    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

application:
  bucket:
    name: elasticbeanstalk-us-east-1-416927159758


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080

